/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BatchRouteImport } from './routes/batch'
import { Route as PredictorRouteImport } from './routes/predictor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchRoute = BatchRouteImport.update({
  id: '/batch',
  path: '/batch',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictorRoute = PredictorRouteImport.update({
  id: '/predictor',
  path: '/predictor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/batch': typeof BatchRoute
  '/predictor': typeof PredictorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/batch': typeof BatchRoute
  '/predictor': typeof PredictorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/batch': typeof BatchRoute
  '/predictor': typeof PredictorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/batch' | '/predictor'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/batch' | '/predictor'
  id: '__root__' | '/' | '/batch' | '/predictor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BatchRoute: typeof BatchRoute
  PredictorRoute: typeof PredictorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch': {
      id: '/batch'
      path: '/batch'
      fullPath: '/batch'
      preLoaderRoute: typeof BatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictor': {
      id: '/predictor'
      path: '/predictor'
      fullPath: '/predictor'
      preLoaderRoute: typeof PredictorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BatchRoute: BatchRoute,
  PredictorRoute: PredictorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
